name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  docker-publish:
    uses: HelixSpiral/reusable-workflows/.github/workflows/publish-docker.yml@v0.0.2
    with:
      registry: ghcr.io
      image-name: helixspiral/stress
      image-version: ${{ github.ref_name }}
